default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: dvm
  password: thewinteriscoming
  host: 212.28.75.79
  port: 5432

development:
  <<: *default
  database: football-factory

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
